### ISSUE TITLE
filewatcher loops infinitely when executing a script that invokes ssh

### ISSUE THREAD

**Issue by proteo** [filewatcher/filewatcher#113] opened 2020-03-10 02:26 UTC
Hi there. I'm using this command to watch changes on a directory with CSS files:

```bash
filewatcher -E 'css/*.css' 'touch-css.sh $FILENAME'
```

It executes a bash file called `touch-css.sh` that uses the name of the modified file to inform a different server about the updated file:

```bash
#!/bin/bash
set -e

LOCAL=Users/proteo/Sites
REMOTE=var/www/sites

# Modifies the path to match the location on the server
FILE=$(echo $1 | sed "s,$LOCAL,$REMOTE,g")

# Update the file in the remote server.
ssh proteo@10.0.1.224 "touch $FILE"

echo "Updated $FILE"
```

The process is (mostly) working, except that the `ssh` line makes filewatcher to enter in a loop, executing the script over and over infinitely, as if the modified file would be changing every second. As soon as I remove that line, everything works as expected.

It's kind of weird but if I comment the `ssh` line when filewatcher is looping, as soon as I save the change the loop is terminated, so it's evident that somehow filewatcher is affected by the command.

Thanks in advance for your help.

**Comment by AlexWayfer** [comment] 2020-04-15 22:55
@proteo thank you for your report! 

Did you try the `-t` flag?

https://unix.stackexchange.com/questions/119894/single-command-to-login-to-ssh-and-run-program

I guess it can help even with Filewatcher, as with anything else.

Just to stop SSH session after a command.

**Comment by proteo** [comment] 2020-04-17 15:34
Hi @AlexWayfer , thanks a bunch for your response.

Yes, I tried with the -t flag, but the only difference that makes is to add a "Connection to 10.0.1.224 closed." message to each iteration in the loop.

I've also tried with something like this, but still won't work:

`ssh proteo@10.0.1.224 "touch $FILE &> /dev/null &" &`

Please feel free to close this if you think it's not a Filewatcher issue, or let me know if I you want me to do further testing.

**Comment by AlexWayfer** [comment] 2020-04-17 20:48
OK, let's find the problem out.

I've reproduced environment which you've described.

And I see correct work of `filewatcher` (`master` version):

```
> ../bin/filewatcher -E 'css/*.css' './touch-css.sh $FILENAME'
/home/debian/css/test.css
Updated /home/debian/css/test.css
/home/debian/css/test.css
Updated /home/debian/css/test.css
/home/debian/css/test.css
Updated /home/debian/css/test.css
/home/debian/css/test.css
Updated /home/debian/css/test.css
/home/debian/css/test.css
Updated /home/debian/css/test.css
```

(All local scripts placed in `filewatcher/test/`, remote is `/hone/debian/`)

I don't see any issues.

> The process is (mostly) working, except that the ssh line makes filewatcher to enter in a loop, executing the script over and over infinitely, as if the modified file would be changing every second. As soon as I remove that line, everything works as expected.

Which loop? How it looks?

I don't see any infinity loop. Multiple outputs was when I tried to spam `Ctrl-S` on CSS file (trying to reproduce "if the modified file would be changing every second", I don't know how to make it in another way).

**Comment by proteo** [comment] 2020-04-17 21:40
OK, I've recorded a couple of screencasts to show you the issue. First, the result of running the command **without** the `ssh` command. You can see the output of the command in the upper window, printing the `Updated ...css` message only when I do a change and save the file (lower window):

![Filewatcher-good mov](https://user-images.githubusercontent.com/376077/79616068-20ccc680-80d2-11ea-87aa-2da7eae874a4.gif)

Now, this is the result of enabling the `ssh` command in `touch-css.sh`. As you can see, the command keeps printing the same message until I manually cancel it (`CTRL+C`) even when I've changed the file just once:

![Filewatcher-bad mov](https://user-images.githubusercontent.com/376077/79616218-786b3200-80d2-11ea-81e1-93d79641e28c.gif)

**Comment by AlexWayfer** [comment] 2020-04-17 22:31
> Edit:
> I'm running macOS 10.14.6, and the remote computer is running Ubuntu server 18.04. `filewatcher -v` reports: filewatcher, version 1.1.1 by Thomas Flemming 2016

Can you please to switch to `master` version of `filewatcher`?

I can record a screen with the similar usage and without loop… server is Debian 9, local is Arch Linux. But I think you trust me. 

I want to discover this.

Steps as I see:

1. Clone the repo and try the same with version in `master` branch.
2. Add logs (like `puts` or something else) to different steps, to know what happens in the loop.

I'll try to do my best to reproduce this. It can be Filewatcher issue so I'm not going to close this.

**Comment by AlexWayfer** [comment] 2020-04-17 22:33
I can't reproduce it with stable version (from RubyGems) by the way, so you can skip the first step testing, just clone to add debugs please, if it's not hard to you.

**Comment by AlexWayfer** [comment] 2020-04-17 22:35
And please re-check the content of shell script. Your previously sent version looks like just "update mtime of file (touch it) on server when it changes locally", without some rewriting (for example, via `scp`). I don't understand the purpose of this.

**Comment by AlexWayfer** [comment] 2020-07-20 18:52
@proteo friendly reminder, I still wait additional information.

**Comment by AlexWayfer** [comment] 2020-09-17 18:29
I'm closing this issue due to inactivity. Feel free to write additional information, we can re-check it and investigate more detailed.

**Closed by AlexWayfer** 2020-09-17 18:29 UTC
