### ISSUE TITLE
The filewatch does not work if files are creating too fast

### ISSUE THREAD

**Issue by zhiyuanouyang** [filewatcher/filewatcher#101] opened 2018-12-13 20:03 UTC
Hi,
I find a issue using the gem. If the files in the watching dirs are creating too fast, say almost less than tens of milliseconds, the filewatcher does not trigger the file creation. How should I deal with this situation if the files need to be monitored in such a short time?

**Comment by AlexWayfer** [comment] 2018-12-13 20:08
Filewatcher check files with specified `interval` (100 ms by default) and has `every` option (disabled by default). Please, read `README`. Does it help?

**Comment by AlexWayfer** [comment] 2018-12-13 20:35
> If I'd like to make it faster response, do I need to set it to a smaller interval?

Yes.

> I find the default is 0.5 second.

Oops, sorry, my mistake. You're right.

---

By the way, are you sure that you understood `every` option? Filewatcher can has even 1 second interval and returns the Hash of all changed files in this second.

**Comment by AlexWayfer** [comment] 2019-03-17 00:09
I would like to hear a feedback, if I can. :slightly_smiling_face:

**Comment by AlexWayfer** [comment] 2019-06-24 22:44
I'll close it for now. I hope, the issue is resolved. I can answer and re-open for additional questions.

**Closed by AlexWayfer** 2019-06-24 22:44 UTC
